# https://docs.astral.sh/ruff/rules/
line-length = 120
target-version = "py39"
exclude = [".ruff_cache", "**/.pytest_cache", "**/venv"]
[lint]
select = ["ALL"]
ignore = ["B011", "N", "BLE", "C901", "COM", "D", "E741", "EM101", "ERA001", "G004", "PLC0415", "PLR0913", "PLR2004", "PT015", "S101", "T201", "TRY003"]
extend-select = ["D100"]
# N = pep8-naming
# BLE = flake8-blind-except
# C901 = complex-structure
# COM = flake8-commas
# D = Documentation
# D100 = Module documentation
# E741 = ambiguous-variable-name
# EM101 = Exception must not use a string literal, assign to variable first
# ERA001 = commented-out-code
# G004 = logging-f-string
# PLC0415 = `import` should be at the top-level of a file
# PLR0913 = Too many arguments in function definition
# PLR2004 = magic-value-comparison
# S101 = assert used
# T201 = print used
# TRY003 = Avoid specifying long messages outside the exception class
